### ISSUE TITLE
Feedback after checking out the ample client on the ampache demo site.

### ISSUE THREAD

**Issue by xekon** [mitchray/ample#1]
I just checked out the ample client on the ampache demo site.

I see that the pages for Playlists and Smartlists are fully responsive, love that!

The Artists and Albums landing page that shows Newest, Random, also looks very nice and responsive.

When you click "All Artists" or "All Albums" there does not seem to be a grid view, only the list view that kinda looks like a spreadsheet. Do you have plans to also add a tiled grid view for "All Artists" and "All Albums"?

The Genres page there is an affect of two scrollbars, the whole page, and then the genre list within, I think it might be better if the inner element did not scroll, so that you only need to scroll the main page, however that is just my opinion on that.

Insights: Recent and Newest looks to be fully responsive, however if you go to insights: Trending and Forgotten , it does not have that same nice responsive layout, it adds horizontal scroll bars.

On the pages that use the spreadsheet appearance, such as Genres and Insights: Top rated. I think the current table layout with the borders looks a bit dated, I actually think the list view of the base ampache that simply uses alternating colors for each row looks a little more modern.

Some of these are my personal opinion, and this post is meant to be constructive, a lot of Ample actually seems to be a lot more responsive than the stock Ampache UI, so I do really like a lot of the elements of Ample, also the left navigation menu also feels more unified / modern.

I also like the dark/light theme that is easily toggled.

The page for an individual artist that shows discography, popular songs, all songs, etc. is a very beautiful page!
Likewise the page for an individual album also looks very beautiful.
Also the layout of the songs for an individual album, has a nice table appearance(it looks modern), something like this might be a better table layout for pages such as genres, "all artists", "all albums", "insight:top rated"

I noticed artist shows the image in a circle, I like the look of the images on albums better where it just has a rounded corner, cutting it down to a circle would chop off important parts of some of my artist images.

this table layout has a dated look:
![2021-09-07_19-45](https://user-images.githubusercontent.com/106644/132438905-19e8f108-cf38-41dc-9307-bf7e00c8b5ad.png)

this is the table layout on stock ampache which I like better:
![2021-09-07_19-55](https://user-images.githubusercontent.com/106644/132438980-cc32471c-26ff-4519-964c-dd8138864fb4.png)

Here is the table layout from ample individual album song list, which I also really like:
![2021-09-07_19-53](https://user-images.githubusercontent.com/106644/132439050-780be351-a594-4836-a45c-0010481d50cc.png)

I hope some of this is helpful, will be keeping a close eye on Ample :)

**Comment by mitchray** [comment]
Thanks for the feedback!

**Comment by mitchray** [comment]
I'm in the process of rebuilding the listing component to make it easier to support future changes like column resizing (done), column hide/show (future) and grid view (future)

**Comment by xekon** [comment]
That sounds awesome!
