### ISSUE TITLE
[Feature Request] new view mode "All Albums" and "Genre>Albums" similarly to the "Newest Albums"

### ISSUE THREAD

**Issue by Jieiku** [mitchray/ample#13]
When you click Albums from the left menu, the landing page displays "Newest Albums" you can repeatedly click the "+" to load more. What you end up with is a nice grid view with large album arts.

I would love it if I could browse "All Albums" and "Genre>Albums" in a similar view, a paged view that loads x number of items in this format:

![Screenshot 2022-04-24 at 13-55-57 Ample](https://user-images.githubusercontent.com/106644/164996307-5a0a27b6-39ce-41af-8ee1-becd0602475b.png)

EDIT: I forgot that you actually planned this, so looking forward to it: https://github.com/mitchray/ample/issues/1#issuecomment-920000292

**Comment by mitchray** [comment]
Paginated grid views added in 0.36.0

**Comment by Jieiku** [comment]
This is Freaking Incredible, Thank you so much! I love it!
