### ISSUE TITLE
[Feature Request] configurable value for the amount of radius to apply to artist images.

### ISSUE THREAD

**Issue by Jieiku** [mitchray/ample#14]
using circle works for majority of artist pictures but I would prefer the square with rounded corner look that  the albums displays, otherwise some of the pictures dont get cropped quite right:

![2022-04-24_14-08-05](https://user-images.githubusercontent.com/106644/164996616-56e67ce8-a903-46b7-b91a-92e5b620ea1a.png)

**Comment by mitchray** [comment]
Artists are circular to differentiate from albums and as you mentioned it works for the majority of pictures

I'm aiming to keep Ample as configuration-free as possible, so adding an option to control the border-radius of artist images is not something I'm open to

I can recommend something like Stylus to override the border-radius with custom CSS

Chrome: https://chrome.google.com/webstore/detail/stylus/clngdbkpkpeebahjckkjfobafhncgmne?hl=en
Firefox: https://addons.mozilla.org/en-US/firefox/addon/styl-us/

**Comment by Jieiku** [comment]
I figured it out:

```bash
sudo sed -i 's/border-radius:50\%/border-radius:7px/' /var/www/ampache/public/ample/public/build/bundle.css
```
