### ISSUE TITLE
[Feature Request] Paged results for genres.

### ISSUE THREAD

**Issue by Jieiku** [mitchray/ample#15]
When I currently click Genres > Classic Rock > Albums , it takes quite a while to load all 1200+ albums (1,050 requests, 17 seconds)

Paged results would be useful in loading things faster.

**Comment by mitchray** [comment]
Pagination added in 0.36.0

**Comment by Jieiku** [comment]
Freaking killer Dude! Will be using Ample as my primary front end now!
