### ISSUE TITLE
Bug? F5 to refresh seems to only work on entry page.

### ISSUE THREAD

**Issue by Jieiku** [mitchray/ample#16]
My entry page is as expected: https://ampache.example.com/ample/

I can navigate and use Ample no problem, but if I hit F5 to refresh the page on another page other than the main entry page I get 404 Not Found.

I am thinking this may be due to my nginx configuration, found a similar post here: https://github.com/mitchray/ample/issues/8

If I find a solution I will be sure to follow up and post it here.

**Comment by mitchray** [comment]
Does this get it working? https://github.com/mitchray/ample/wiki/NGINX-rewrite

**Comment by Jieiku** [comment]
mmm, let me try adding that now and see what happens.

**Comment by Jieiku** [comment]
Yep, that did the trick, thanks a lot!
