### ISSUE TITLE
Bug? Recently Played does not actually display the Most recently played

### ISSUE THREAD

**Issue by Jieiku** [mitchray/ample#17]
When you click "Recent" from the INSIGHTS menu on the left, the items displayed are indeed recently played items, but they are not the most recently played items, you can see this by comparing the recently played items displayed in the regular Ampache, you can also see this happening just by looking for the last few songs you played and seeing they are not there.

**Comment by mitchray** [comment]
You would need to refresh that page to get the latest information, the same as ampache/stats.php?action=recent

The 'recently played' on the Ample home page refreshes when you play a new song, similar to Ampache's home page though that is on a timer

**Comment by Jieiku** [comment]
hmmm I am probably just noticing whatever the difference is on the timer, what is the timer interval?

**Comment by Jieiku** [comment]
Yep! thats what it was! If a song is played in Ample then the list is updated, but if the song is played in the base Ampache web UI, then the recent list in Ample does not update until the next song is played in Ample.

**Comment by Jieiku** [comment]
Oh I think you were saying that the Base ampache one updates on a timer.

Is there a way to force an update of the Ample one via command line? If so I could setup a cron job to run every 10 minutes.

Eventually I hope to just use Ample for everything, mostly just waiting for the grid view on albums/artists.

I like the player/playlist much better in Ample, but I like browsing with the larger thumbnails in grid layout.

**Comment by mitchray** [comment]
Yeah its just a basic method at the moment which doesn't really account for multi-user setups

Its something I'll revisit in the future
