### ISSUE TITLE
Bug? clicking images in search results not working

### ISSUE THREAD

**Issue by Jieiku** [mitchray/ample#18]
If I search for "Ozzy" I have to click the text, clicking the image is not working.

The image does appear to be a link, and clicking it even update the address bar of the browser, but it does not actually take me there. To actually get the link to load I have to click on the text.

![2022-04-24_14-55-07](https://user-images.githubusercontent.com/106644/164998298-60496477-6487-48cf-86b4-1ba8f57a5e66.png)

**Comment by mitchray** [comment]
Fixed in [9bd7b21](https://github.com/mitchray/ample/commit/9bd7b211437319f05d22285ccb5f830af1747b1e)

**Comment by Jieiku** [comment]
right on, thank you!
