### ISSUE TITLE
[Bug] Column resize - All albums, index is off after Date?

### ISSUE THREAD

**Issue by Jieiku** [mitchray/ample#19]
You can resize the first couple columns, but it gets weird when you use the handle just after the date header.

I would think the column header should line up with whats in the column, otherwise it gets a very disconnected appearance.

![ample-all-albums-columns](https://user-images.githubusercontent.com/106644/165232721-54a92e3b-af9b-4965-9956-c961b48eeb78.gif)

Same issue, all Artists... maybe it is because of the controls column that does not have a header?

edit: nope I dont think that is the issue... seems to also do it on the genres page (the one that lists all genres)

**Comment by mitchray** [comment]
Dates & numbers are right-aligned, but the headers are all left-aligned

Is this what you mean?

**Comment by Jieiku** [comment]
Ah yes! thats whats happening. I think it would  be more natural if the text in the header followed suit with whatever the column below does.

So if it is a number or date column then make the column header for those right aligned.

**Comment by mitchray** [comment]
I'll look at that for the next iteration of that component

**Comment by Jieiku** [comment]
Honestly, now that I understand whats happening I can use it easily enough, just gotta be careful to keep the number and date columns narrow. My brain just could not connect what was happening when I was resizing this, I thought it was broken.

**Comment by mitchray** [comment]
Come to think of it those kinds of fields don't really need to be resizable at all...

Updated in https://github.com/mitchray/ample/commit/2ba562ad7b5829a009238b030891a8ea8ad58991

**Comment by Jieiku** [comment]
I had considered that as well. Awesome, thanks.
