### ISSUE TITLE
Quick Question - what information / tags does the new Type column display?

### ISSUE THREAD

**Issue by Jieiku** [mitchray/ample#20]
Quick Question - what information / tags does the new Type column display?

(my type column is empty but im assuming that is because its looking for a tag I don't have set)

Thanks for the update, love the idea of health checks!

**Comment by mitchray** [comment]
Typically its something like 'album, ep, single, compilation, live' etc

If you have ```Album - Group per release type``` enabled in Ampache -> Server -> Interface then the different types will be grouped together. ```Album - Group per release type sort``` will define and control the order they should appear

![firefox_zRhkBsfjs4](https://user-images.githubusercontent.com/5735900/165642347-4fe53dbf-a94e-4b99-a70b-e576c9fb12a7.png)

**Comment by mitchray** [comment]
More info https://musicbrainz.org/doc/Release_Group/Type

**Comment by Jieiku** [comment]
OH COOL! thanks for the info and the awesome new feature.
