### ISSUE TITLE
[ Feature Request ] Make "All Artists" & "All Albums" The default view or remember last viewed.

### ISSUE THREAD

**Issue by Jieiku** [mitchray/ample#21]
Once you have a fairly Large collection "Recently Updated" becomes something you may rarely look at and you will most of the time want to view "All"

For this reason I think it would be more convenient to make "All" the default, but if you disagree maybe there is a way Ample can remember the view that I last used? That way if I click Artists or Albums from the left I will return to the "All" view.

**Comment by mitchray** [comment]
I'd like to keep the dynamic stuff as the default view (Recently Updated for Artists, and Newest for Albums)

Again, I'm aiming to keep Ample as configuration-free as possible, so one extra click to get to 'All' is acceptable to me vs adding another setting
