### ISSUE TITLE
[Feature Request] optimal count to evenly fill usable area For artist/album grid view.

### ISSUE THREAD

**Issue by Jieiku** [mitchray/ample#22]
I have a 1920 x 1080 display, I believe this is also the most common Resolution.

For the display of Grid view All Artists I am suggesting 54 instead of 50:

![Screenshot 2022-05-16 at 17-16-25 Ample](https://user-images.githubusercontent.com/106644/168702387-d8935937-000e-4b1e-8618-8eaa7f4762d4.png)

For the display of Grid view All Albums I am suggesting 56 instead of 50:

![Screenshot 2022-05-16 at 17-17-36 Ample](https://user-images.githubusercontent.com/106644/168702467-cc7700d6-5861-47cf-9799-9365c1608c8a.png)

The default of 50 would be less of an issue if it remembered what I last set the page Limit to, but I still think defaults that fill the page are a good idea.

**Comment by mitchray** [comment]
I'll have it save limit values for Artists/Albums/Songs etc

**Comment by mitchray** [comment]
Added, available in next release
