### ISSUE TITLE
[Feature Request] Make Player / Playlist area collapsable for more viewing area for browsing.

### ISSUE THREAD

**Issue by Jieiku** [mitchray/ample#23]
Ampache when it does not have music playing, like when you first visit, does not have the player obscuring part of the screen, this is useful while browsing. I was thinking a way to collapse the player at the bottom would be nice, maybe an unobtrusive collapse button in the bottom left?

![2022-05-16_18-47-18](https://user-images.githubusercontent.com/106644/168711612-7e87a50d-ce5f-4911-b930-d29e2409b55a.png)

Would also be cool if the search, logout, dark/light selector could be collapsed into the left menu bar, but I can see how that might be more of a design challenge. (The most difficult part would be the search box, because when the left is collapsed you would have to use a search icon that pops open a search box or something)

**Comment by mitchray** [comment]
Unlikely to make those kinds of changes to the interface at this stage
