### ISSUE TITLE
[Bug] Artists > ALL > Click into artist > now click back (you dont return to ALL view, instead you return to Recently Updated.)

### ISSUE THREAD

**Issue by Jieiku** [mitchray/ample#24]
I just noticed something:  when you click into Artists > ALL > Click into an artist > now click back

What you see is that you do not go back to the "ALL" listing that you were at previously, instead you end up at "Recently Updated."

This same behavior applies to Albums.

This might also close the feature request I opened (I am not sure): https://github.com/mitchray/ample/issues/21

PS: I absolutely love the "By Year" feature that you added to Albums, that is really slick! I also really love the Row of Letters to jump to the page with a particular letter. It also seems you made some things even more responsive, different page widths all display great! I LOVE IT!!! (even the LIST view collapses like a ninja!)

**Comment by mitchray** [comment]
As part of other changes the browser back/forward now remembers which tab you were on when you left that page

**Comment by Jieiku** [comment]
Thank You! back button works now.
