### ISSUE TITLE
[Feature Request] Responsive Advanced Search.

### ISSUE THREAD

**Issue by Jieiku** [mitchray/ample#25]
You have done an amazing job of making everything responsive, I absolutely LOVE IT!

I noticed one thing is not yet fully responsive, that is the controls in the box at the top of the Advanced Search page and Multi-rater page.

I would prefer that the box take up more room vertically (more rows) as the page becomes narrow, so that all controls are easily usable on a phone.

With how much work you put into making things responsive I am sure your already aware of it, so this issue can just be used to track this feature.

**Comment by mitchray** [comment]
Added in [ff2addb](https://github.com/mitchray/ample/commit/ff2addbd6932efb3ed0fc04d26009344e1e56566)
