### ISSUE TITLE
Any chance this could be transplanted to nextcloud music?

### ISSUE THREAD

**Issue by xinstein** [mitchray/ample#26]
I understand that this has to be installed alongside ampache server.
But it seems the only coherence with the ampache server is the serverURL in stores/server (correct me if I'm wrong).

Nextcloud on the other hand also uses php and there's the music app which provides both ampache and subsonic interface, as well as a not-so-satisfactory webui.

I'm thinking if this could be installed standalone and the serverURL be made configurable, it might just work well with nextcloud music.

Is this doable?

**Comment by mitchray** [comment]
Hey, Ample is designed as a drop-in companion client for an Ampache server specifically, so my assumption is it wouldn't work

If Nextcloud/music has support for the **entire** Ampache API, including things like [user_preferences](https://ampache.org/api/api-json-methods#user_preferences) then maybe... though I'm guessing it would just be more general artists/albums/songs

If you're interested and able to test it, override the [server URL](https://github.com/mitchray/ample/blob/main/src/stores/server.js#L19) and see what happens

**Comment by xinstein** [comment]
I tried it, here's my Dockerfile:
```Dockerfile

FROM php:8-apache

RUN apt-get update ;
RUN apt-get install -y git ;
RUN cd /var/www/html/; \
    https_proxy=192.168.2.101:1080 git clone https://github.com/mitchray/ample.git ; 

RUN apt-get remove --purge -y git; \
    apt-get autoremove --purge -y;

RUN a2enmod rewrite ;

##### clear cache
RUN rm -rf /var/lib/apt/lists/* ;
```

Then I open https://mydomain:myport/ample/index.php (the protocol and the domain and port are my reverse proxy):
- No error printed on the server side.
- The page title "Ample" displays, but page is blank.
- Some error occurs on the browser console:
```
bundle.js:1 
        
       Uncaught SyntaxError: Unexpected token '<' (at bundle.js:1:1)
cqfill.min.js:1 
        
       Uncaught (in promise) Error: (https://mydomain:myport/ample/public/build/bundle.css): Advanced beyond the end
    at S (cqfill.min.js:1:4083)
    at L (cqfill.min.js:1:3637)
    at z (cqfill.min.js:1:3712)
    at B (cqfill.min.js:1:3849)
    at Q (cqfill.min.js:1:3916)
    at C (cqfill.min.js:1:2655)
    at t (cqfill.min.js:2:444)
S @ cqfill.min.js:1
L @ cqfill.min.js:1
z @ cqfill.min.js:1
B @ cqfill.min.js:1
Q @ cqfill.min.js:1
C @ cqfill.min.js:1
t @ cqfill.min.js:2
await in t (async)
(anonymous) @ cqfill.min.js:2
p @ cqfill.min.js:2
(anonymous) @ cqfill.min.js:2
(anonymous) @ cqfill.min.js:2
site.webmanifest:1 
        
       Manifest: Line: 1, column: 1, Syntax error.

```
-

**Comment by mitchray** [comment]
I'm going to say it isn't feasible to support anything other than a standard Ampache server

**Comment by paulijar** [comment]
Sorry to necro-post, but as the developer of Nextcloud Music, I find this topic interesting. I'm currently in the process of adding support for Ampache API versions 5 and 6 to Nextcloud Music. While doing that, I'd like to make it compatible also with Ample. 

I actually already have a partially compatible version on my work area, where some of the views of Ample work fine. But to make it complete, some significant effort is still needed. The most important missing piece is the `advanced_search` which is used heavily on Ample but not yet supported on Nextcloud Music. Before this, I haven't seen any client using this part of the API, and hence I have opted not to invest time and effort on it.

**Comment by mitchray** [comment]
Well the good news is all the API calls have been extracted to [javascript-ampache](https://github.com/mitchray/javascript-ampache), so it may just be a matter of changing [these](https://github.com/mitchray/javascript-ampache/blob/c1d8fac174a99d23e39fec228709b244231026fa/src/base.ts#L39) [two](https://github.com/mitchray/javascript-ampache/blob/c1d8fac174a99d23e39fec228709b244231026fa/src/base.ts#L62) lines to your Nextcloud Music URL

Test that out and if it works then I can add that option into the library

**Comment by mitchray** [comment]
Interesting to learn you were able to get it at least partially working with Ample 👍

Keep me posted if/when you add advanced_search support

**Comment by paulijar** [comment]
The Nextcloud/ownCloud Music v1.9.1 was released a couple of days ago and it works rather nicely together with Ample.

There are a few limitations, though:
1. It's possible to set up Nextcloud or ownCloud server to use either MySQL/MariaDB, PostgreSQL, or SQLite as the DB backend. Out of these, SQLite does not have native support for regular expressions, and hence, the Ampache advanced search with regex pattern will not work on installations using SQLite. In addition to being available in the Advanced search view, Ample uses regex searches under the hood in a few places and these features will not work with SQLite.

2. The advanced search rules "sounds like" and "doesn't sound like" work only with MySQL/MariaDB.

3. In the advanced search view, majority of the available rules are supported but some are not.

4. The format used for the method `user_preference` is that of Ampache 6.0.1 or later. Hence, the view using this method does not work on the latest Ample release 2.0.2 but I can see that there is already on unreleased API update in this repository.

**Comment by paulijar** [comment]
Update: Nextcloud Music v1.11.0 now fixes the DB-type limitations mentioned above. That is, the regexp searches now work fine also on SQLite, and "sounds like"-type of searches work also on SQLite and PostgreSQL. On the latter, this requires installing the extension `fuzzystrmatch`, though. Also, quite a few bugs were fixed from various cases of the advanced search.
