### ISSUE TITLE
[Feature Request] Apply those Very Cool Genre Cover Art Styles to the Smartlists/Playlists

### ISSUE THREAD

**Issue by Jieiku** [mitchray/ample#27]
Would love it if the smartlists & playlists had the same style as the genres. (Or something different but equally cool!)

smartlists:
![2022-05-26_15-50-38](https://user-images.githubusercontent.com/106644/170592037-54bd4820-af53-40a9-8ba9-ecb29d195326.png)

genres:
![2022-05-26_15-45-37](https://user-images.githubusercontent.com/106644/170591562-482185f9-59d3-43b8-b3f8-13a19b4e5dfd.png)

**Comment by mitchray** [comment]
Playlist/Smartlists now have dynamic art in [0.42.0](https://github.com/mitchray/ample/releases/tag/0.42.0)

![firefox_Z735d8ipW7](https://user-images.githubusercontent.com/5735900/187367451-6f0cb6dd-cc52-4980-be2e-92065191697e.png)

**Comment by Jieiku** [comment]
That looks really awesome! Thank you!
