### ISSUE TITLE
[Feature Request] YES! THANK YOU! can we please have this traslate to desktop notifications?

### ISSUE THREAD

**Issue by Jieiku** [mitchray/ample#28]
Thank you SOOOOOOOO much for this new notification system. I absolutely love the notification for unrated song. I actually previously created a request for such a feature: https://github.com/ampache/ampache/issues/2735

Would love it if your Notification system sent the Notification to the Operating System.

The base Ampache does this somehow. Firefox prompts me to send notifications, and then the notifications come in on my KDE notification tray widget. I have no idea if you use KDE or are familiar with it, but here are screenshots from KDE with Firefox and the regular Ampache:

![2022-05-26_18-07-28](https://user-images.githubusercontent.com/106644/170608317-a954d8a1-cd94-46ce-92fe-0a0bbb02d3d5.png)

![2022-05-26_18-04-15](https://user-images.githubusercontent.com/106644/170608081-f29b9052-e8e8-4e34-ab23-0bdad5a683dd.png)

**Comment by mitchray** [comment]
Only planning to keep it in the player
