### ISSUE TITLE
White Page Browser /ample

### ISSUE THREAD

**Issue by topa-LE** [mitchray/ample#3]
Hello, 

wanted to use your themes. Complete Ample folder after Ampache Public folder.

Call the page: https://dyndns.ampache.de/ample

Result: White page. :-( Now I don't know if it's because of the apache2.conf, because maybe the location is missing.

Do you have a tip, your theme looks very good and would like to use it.

**Comment by topa-LE** [comment]
With Nginx web server exactly the same problem.
Where could you solve the problem?

**Comment by mitchray** [comment]
> **Edit:** Error found, Done ;-)

Hi, so you got it working?

**Comment by topa-LE** [comment]
Yes, was my stupid mistake ;-) Will now times me purely work there. Super Theme Very good work! If you have any questions I will contact you.

**Comment by mitchray** [comment]
👍
