### ISSUE TITLE
Have you implemented the playlist_remove_song API ?

### ISSUE THREAD

**Issue by feizhoulv** [mitchray/ample#32]
I can't find the Remove Song button in the playlist on the interface.

Have you implemented the playlist_remove_song API ?

**Comment by mitchray** [comment]
It used to be there but was removed a while ago while I was building other things, and haven't had a good reason to revisit it as I don't really use the regular playlists...

Anyway I've just re-implemented it, so thanks for the push! Will do a bit of testing to make sure its all OK but should be in the next release

![firefox_z4rHdIqyWB](https://user-images.githubusercontent.com/5735900/184899309-40322772-2b81-4a2c-b7b2-7d2955538b4d.png)

**Comment by mitchray** [comment]
Added in [0.41.0](https://github.com/mitchray/ample/releases/tag/0.41.0)
