### ISSUE TITLE
How to change the logo to use my own logo?

### ISSUE THREAD

**Issue by daoudi5** [mitchray/ample#39]
Hi,
Thank you for the good work you did :) 
I want to know if possible to change the logo and use my own logo image or text?

Best regards,

**Comment by mitchray** [comment]
There isn't a built in option to change the logo, but if you really needed to you can override it with some custom CSS using something like the [Stylus browser extension](https://github.com/openstyles/stylus)

**Comment by daoudi5** [comment]
Hi,
Thank you for your advice. It's work :)
but when i'm in an album the number of song is correct and the list is not I just see 2 of 75 elements displayed.
Do you know where could be the problem?
Best regards,
