### ISSUE TITLE
Catalog Typ: Video (mp4 Stream)

### ISSUE THREAD

**Issue by topa-LE** [mitchray/ample#4]
In Default Themes you have the possibility to record and also stream video .mp4 via the catalog Type: Music Clips. 

Do you not have the menu for videos in the "ample" yet?
Is it perhaps planned? Currently I don't see it, although there is a video catalog created in the ample.

Best thanks

**Comment by mitchray** [comment]
Ample is music only

**Comment by topa-LE** [comment]
Could you make .mp4 for video?
Would be really mega good!

Because so it does not quite fit the standard.

**Comment by topa-LE** [comment]
This would be a huge value add to the super good theme for Ampache. Basically, the complete implementation to the default is currently missing.
