### ISSUE TITLE
question!

### ISSUE THREAD

**Issue by justinweichTV** [mitchray/ample#41]
i have moved the ample folder to /public/ as explained, but nothing has changed!, at /public/ample everything is just white, what should i do to use the desgin ?

**Comment by mitchray** [comment]
Are you using a pre-built [release](https://github.com/mitchray/ample/releases) or straight from the repo?

**Comment by justinweichTV** [comment]
i'm not sure, i followed this guide: https://wiki.ubuntuusers.de/Ampache/

**Comment by mitchray** [comment]
Once you have Ampache setup and can access it, add ```/ample``` to your Ampache server address. e.g yourampache.com/ample or localhost/ampache/ample

**Comment by justinweichTV** [comment]
So do not move the folder to /public/ folder Right ?

**Comment by mitchray** [comment]
Just to clarify the steps:

1. Install Ampache and setup a music catalogue within it (do not continue unless this is working)
2. Download [the pre-built release of Ample](https://github.com/mitchray/ample/releases/download/1.0.0/ample_1.0.0.zip)
3. Copy the ```ample``` folder from that into the ```public``` folder of your Ampache installation
4. Access Ample by adding ```/ample``` to your Ampache website address in your browser

**Comment by justinweichTV** [comment]
It didn't work. A blank white page.
Video: https://1drv.ms/u/s!AubUEEgXFkKvgWRAVQIiqlLOAgEY

**Comment by mitchray** [comment]
There was a warning at the start there "You must update your DocumentRoot to the new path"

**Comment by justinweichTV** [comment]
I have trying to fix it with the introduction but now it looks like this ![IMG_20230108_065327.jpg](https://user-images.githubusercontent.com/64624657/211182577-bca9b45a-a898-40d4-8d41-b09b454972f1.jpg)

Help.

**Comment by justinweichTV** [comment]
After Server restart it turns Normal but the error Still there.

**Comment by justinweichTV** [comment]
Nevermind. I have fixed it & now your design works! Thanks!
