### ISSUE TITLE
Different install location

### ISSUE THREAD

**Issue by CommandCrafterHD** [mitchray/ample#42]
Is it possible to use Ample from a different install location than Ampache?
I'd like to be able to have a separate subdomain for both of them, which would be easy to accomplish with 2 different virtual hosts (running apache). But ample becomes entirely unresponsive when it's not in ampache/public.

I did try to build from source (with the root folder set to "/" and the server address specified) but still no luck.
I also tried to just make the ampache/public folder a separate virtual host but got the same unresponsiveness as before.

**Comment by mitchray** [comment]
Not possible sorry, it relies on ```/ample``` in the URL to get the Ampache server URL without having to use a config file

**Comment by CommandCrafterHD** [comment]
Gotcha. Thanks for the quick reply ^^

Out of curiosity, would it *theoretically* be possible if I forked the project/created a branch to implement it myself or is it just a technical limitation that would require too much of a rewrite to work?

**Comment by mitchray** [comment]
Yeah potentially, I think its only these parts

Router path
https://github.com/mitchray/ample/blob/05682cf89d7c528887b1eea7d084d6d15be6a4e5/src/App.svelte#L92

Server path
https://github.com/mitchray/ample/blob/05682cf89d7c528887b1eea7d084d6d15be6a4e5/src/stores/server.js#L6-L8

**Comment by CommandCrafterHD** [comment]
Nice! I'll try getting it set up after work tomorrow then ^^

Thank you very much for the help and the pointers! :)

**Comment by CommandCrafterHD** [comment]
Just created a pull request with my changes, in case you want to give other people the option to use remote servers as well.
(That is assuming what I just pushed isn't too horrible lol)

**Comment by mitchray** [comment]
Glad you got it working! I'll review it when I get the chance
