### ISSUE TITLE
Add Remember Me Feature

### ISSUE THREAD

**Issue by mediadev123** [mitchray/ample#44]
Hey,

is there any way that you can implement a remember me feature? I constantly get logged out of ample and it would be awesome if I didn't have to type my password everytime.

Thanks in advance!

**Comment by mitchray** [comment]
I feel your pain, right now there isn't a way unless the password is stored in plaintext which to me isn't a great option...

There have been recent discussions in Ampache about adding a new perma-auth token which would allow you to remain logged in to clients like Ample, so hopefully that is implemented soon

**Comment by mediadev123** [comment]
Wow thanks for that information. I suppose my mobile client is also saving my password in plaintext, which isn't great... That being said, I can see two ways to "bypass". Maybe there is a way to generate (if necessary) and query and API key from the backend. 

Alternatively, couldn't you just perma save the API key in the client if you login with the API, as saving the API key isn't that big of a deal. 

Thanks for creating this great app though. It looks great and is very easy to use.

**Comment by mitchray** [comment]
I already attempted to use a saved API key but it wasn't very reliable so I shelved it for another day https://github.com/mitchray/ample/commit/8be8a46c7aa085f60c2fc35a8731fc0878164512

Its definitely a QOL improvement to have in the future

**Comment by mediadev123** [comment]
What exactly was the issues with that commit? Do you have any idea what made it unreliable? I would like to help-out if I can

**Comment by mitchray** [comment]
I'm going to close but will potentially revisit if/when the Ampache API is updated to allow this

**Comment by rstefko** [comment]
I would like to re-open this issue to reconsider the option to store credentials in local storage. With owncloud music you generate an API password but still it is username / password login (not api key without expiration). Maybe it could be enabled by a config option?

**Comment by yigitkonur** [comment]
Can't agree more, it keeps logging out every 30 seconds for me which makes this project not usable for me.

**Comment by yigitkonur** [comment]
I completely agree. It keeps signing me out every 30 seconds, making this project unworkable for me. @mitchray, could we possibly address this issue? Is there an option to increase the sign-in duration? I've set up a read-only API in an attempt to fix this, but I'm still getting signed out.

**Comment by mitchray** [comment]
Ampache 6.2.0 added an option for API sessions to never expire: perpetual_api_session

Enable that and you should be good

**Comment by rstefko** [comment]
@paulijar is it possible to increase session in ownCloud music?

**Comment by paulijar** [comment]
For ownCloud Music, the expiry time is currently 6000 seconds (1 hour 40 minutes). The timer is renewed whenever there is an authorized API call. I don't think it should run out while you are actually using the client. But maybe I could make this a configurable value.

What the Ample client could make to improve the situation, would be to ping the API every now and then. With that, the session should not time out while the web page is open even in case the user is not actively using it.

**Comment by mitchray** [comment]
Ample already does that every 15 minutes

https://github.com/mitchray/ample/blob/9c73ce7960b92b0e1864fc9fa58cc3d764af8b28/src/App.svelte#L38

**Comment by rstefko** [comment]
In my case Ample does not logout while being used. Increasing the sessions expiration would help in my case. I will try to edit the code on my side and test. Thanks

**Comment by rstefko** [comment]
Increasing the session helped, @paulijar it would help to have ability to configure session expiration for API in ownCloud Music.

**Comment by paulijar** [comment]
@rstefko I created the issue https://github.com/owncloud/music/issues/1134 for ownCloud Music about this feature request.

**Comment by saibaaimo** [comment]
@mitchray Could you perhaps make API key field a password field? Users could then be able to store the key in their (browser) password manager and easily enter.

**Comment by saibaaimo** [comment]
@mitchray excellent, works well, thank you! :-)
