### ISSUE TITLE
Add Translation/Localization (volunteering)

### ISSUE THREAD

**Issue by sschmidTU** [mitchray/ample#46]
Hello Mitch,
first of all thanks for your beautiful UI and project!
We would like to add translation capability to the project, and would volunteer to write (most of) the translation code and a German translation. We just wanted to ask for your thoughts, and whether you have any ideas or requirements for the implementation (e.g. to get a pull request merged).

Here's an article on localization/translation in Svelte:
https://blog.logrocket.com/implementing-localization-svelte/

Here's a demo for localization:
https://svelte.dev/repl/de39de663ef2445b8fe17b79c500013b?version=3.58.0

Note that personally I'm just getting started with Svelte (though experienced with PHP, JS, etc), but I will obviously get into it for this project.
We already have a working Ampache community server online, and are looking to transition to Ample as it's a vast UI improvement, but we need a German translation for part of our community, as exists in standard Ampache. (and maybe a French one, but we'll definitely do German first)

additional resources:
POEditor (localization management platform with optional automatic translation, free for OS):
https://poeditor.com/kb/open-source-localization

**Comment by mitchray** [comment]
Thanks for checking out Ample, and for your offer to help implement localisation, I've attempted it a few times but haven't found a solution I was comfortable with.

I much prefer the "gettext" method which Ampache uses alongside Transifex (which looks to be a similar service to POEditor), over a key/value system such as in those examples.

I'm currently making a lot of changes to Ample as Ampache v6 is in the works so right now isn't a good time for getting translations working. Once things settle down again I may look into translations again, but I'm not sure on the timelines for that.

**Comment by sschmidTU** [comment]
I also like the Ampache method of translation, so we can definitely settle for that, e.g. in PHP:
```php
$T_PostShout = T_('Post Shout');
```

It's unfortunate that the timing with Ampache 6 doesn't align well, we may have to fork the current version then and add translation ourselves until Ampache 6 is ready. Unless this settles down in a month or so.
I also had the impression that new versions of Ampache tend to be very unstable and introduce a lot of problems and bugs for the first people transitioning. At least I've read such reports for past major Ampache updates. That would be another reason for us to stick with 5.x for the near future.
But of course we are also excited to see Ampache 6 including new features and Ample's version of it eventually!

**Comment by mitchray** [comment]
Yeah thats a possibility, I won't be making any more updates to the ampache5 branch so if you wanted to fork that and manually translate it please be my guest! 

No doubt less work than implementing full i18n

**Comment by sschmidTU** [comment]
Thanks for all the info and help!
By the way, of course we don't want the fork to compete with main ample, we just want to add translation for our project (and for others, if there's interest), and maybe we can then see how to merge/adapt that to main Ample once the Ampache 6 transition has settled.

**Comment by mitchray** [comment]
@sschmidTU I've added German translations, all of which were machine translated so some words might be incorrect.

If you want to take a look (and correct any) you can visit: https://inlang.com/editor/github.com/mitchray/ample
