### ISSUE TITLE
Trim search input

### ISSUE THREAD

**Issue by SimonHova** [mitchray/ample#47]
This sounds like a silly request, but when I am searching for a song from my cell phone, it often auto completes with a space at the end, so the song that I am looking for is gone, until I erase the space.

For example, when my four year old requests the Chipmunks song for the millionth time, I now open the Ampache web interface, type in _chipmunks_, it'll be input as _chipmunks**(extra space)**_ and shows no results. I have to erase the space for it to show the song that she wants to hear.

If you could add the code to trim the extra space for me before sending the search to Ampache, that would be a wonderful gift to me. Thanks again.

**Comment by mitchray** [comment]
That could be easily done but then any search with an intentional trailing space won't work... I do that quite a lot.

I think the solution here is just to be mindful of auto-added spaces as a mobile user, and remove them if desired.
