### ISSUE TITLE
Support for standard media control

### ISSUE THREAD

**Issue by caha321** [mitchray/ample#5]
Hi, first of all I love your client :) To make it even better, it would be very nice if you could add support for [standard media control](https://developer.mozilla.org/en-US/docs/Web/API/MediaSession) (like hardware buttons on a keyboard). 

Thank you!

**Comment by caha321** [comment]
Hi again, thanks for considering it :)
I looked a bit further into this and even found a plugin for [wavesurfer.js](https://wavesurfer-js.org/example/media-session/index.html). I hope it helps you. Thanks again

**Comment by mitchray** [comment]
Thanks that is helpful indeed

**Comment by mitchray** [comment]
I just added the mediasession plugin, will be available in the next release 👍

I don't have any media keys myself but I simulated them with AutoHotKey and it appears to be working

![firefox_lKRhIk4Xrq](https://user-images.githubusercontent.com/5735900/147244921-3e60c555-1570-4785-8677-e6ad5835031d.png)

**Comment by caha321** [comment]
Thank you very much, I'm looking forward to using it soon :)
I will report in case something does not work. Judging by the screenshot the skip buttons seem to be disabled - although that could probably happen when there is only one song in the playlist

**Comment by caha321** [comment]
I just tested the newest release and works perfectly, thank you very much :)
