### ISSUE TITLE
Advanced search rules "Added" and "Updated" are awkward to use

### ISSUE THREAD

**Issue by paulijar** [mitchray/ample#50]
For the advanced search rules "Added" and "Updated", the input is supposed to be in the ISO format like "2023-08-17T23:55". However, in the advanced search view of Ample, the input field is of numeric type in these cases. This means that on Chrome, it's impossible to enter the date like shown above. What's even worse, on Firefox, you can enter the date as a string but any non-numeric input will get converted to "null" when the search query is sent to the server.

Now, the DB used by the Ampache server seems to allow entering the datetime also by leaving the non-numeric characters off like "202308172355". It's also possible to omit the time part like "20230817". Hence, using these search rules is not completely impossible but figuring out the correct way to use them is far from trivial.

Ideally, there could be some kind of date selector widget. But it would already go a long way if there was a string-type input field along with the hint "yyyy-mm-dd".

**Comment by mitchray** [comment]
Thanks for letting me know, added in [8d14b13](https://github.com/mitchray/ample/commit/8d14b1364efc7c898a3d52805e4b6119277c2534)
