### ISSUE TITLE
when choosing an artist its not showing albums

### ISSUE THREAD

**Issue by bfd69** [mitchray/ample#53]
Very nice work !
as soon as i saw it i tried it !
just installed it on a 6.1 ampache (docker), when choosing an artist it shows "Loading" on Release tab without results, while the other tabs are ok.

**Comment by mitchray** [comment]
I've loaded up 6.1.0 but am not seeing any errors... are there any messages in the browser console? (F12)

**Comment by bfd69** [comment]
This afternoon ill try activating debug logs…

Envoyé de mon iPhone

Le 5 janv. 2024 à 12:39, Mitch Ray ***@***.***> a écrit :

﻿

I've loaded up 6.1.0 but am not seeing any errors... are there any messages in the browser console? (F12)

**Comment by bfd69** [comment]
debug didnt gave anything, F12 gave me this : 
![image](https://github.com/mitchray/ample/assets/66788605/80678a3f-702e-4401-a080-c6f37cb77f2d)

**Comment by paulijar** [comment]
I believe this is because the latest released Ample version is not quite compatible with Ampache 6.x.y. My best guess is that this would be already solved by the commit 2fd65a2 but there has been no application releases for a while.

**Comment by mitchray** [comment]
New release https://github.com/mitchray/ample/releases/tag/2.0.3
