### ISSUE TITLE
Does it supports multiple languages? +feature request

### ISSUE THREAD

**Issue by izyspania** [mitchray/ample#6]
Does it supports multiple languages? or i have to edit each file? (maybe it should take the lang from ampache? )

Is it possible to add the register / Lost Password on the login page? (in the same template not an redirect to ampache)

Clicking on the image should take you to the list of Album / Artist view etc.. , names are a bit counter intuitive and small to click on them.

**Comment by mitchray** [comment]
Hi and thanks for taking a look at Ample

Multi-language is not planned, and I'd prefer to leave registration/password handling by Ampache itself

I agree on the images being clickable, its on my own to-do list which I chip away at when I can
