### ISSUE TITLE
Mobile commpatibility

### ISSUE THREAD

**Issue by izyspania** [mitchray/ample#7]
Any plans to make it compatible for mobile?
Great work btw.

**Comment by mitchray** [comment]
Unlikely (maybe one day?), I only listen to music on desktops or with Ultrasonic/subsonic apps if needed on mobile

Mobile and multi-language support are planned for another client which was in development but is currently in hiatus, https://github.com/ampache/ampache/tree/react-client

Ample is just a personal project which meets my own requirements in the mean time, which I'm sharing in case anyone else finds it beneficial

I hope that sets expectations better, thanks again

**Comment by izyspania** [comment]
react-client doesnt seem to build  but ill dig into it. thanks.

**Comment by Jieiku** [comment]
Just adding this as information. I use Dsub without issue, you can find current builds on (F-droid)[https://f-droid.org/]
