### ISSUE TITLE
Feature - Bookmarks

### ISSUE THREAD

**Issue by izyspania** [mitchray/ample#9]
1. Can you add a section for Bookmarks? Would be great if we want to use it with audiobooks.
get_bookmark Api5+
bookmark_create Api5+
bookmark_edit Api5+
bookmark_delete Api5+

2. Continue where you left on different device? (after you logged in check and start to play where u left or can be great to save time to time just in case you reload or close the page)
This is the subsonic api not sure what is the ampache api but it should have some equivalent(it works with this api)
http://your-server/rest/getPlayQueue
http://your-server/rest/savePlayQueue

3. Variable playback speed

**Comment by mitchray** [comment]
Out of scope, focusing just on music
